services:
  web:
    build:
      context: .
      target: development
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - MAIL_USERNAME=${MAIL_USERNAME}
      - MAIL_PASSWORD=${MAIL_PASSWORD}
      - MAIL_DEFAULT_SENDER=${MAIL_DEFAULT_SENDER}
      - MAIL_RECIPIENT=${MAIL_RECIPIENT}